# Generated by Django 5.1.15 on 2026-09-24 00:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('push_app', 'Push (app)'), ('telegram_publico', 'Telegram público'), ('telegram_privado', 'Telegram privado'), ('telegram_interno', 'Telegram interno')], max_length=20)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('leido', 'Leído'), ('fallido', 'Fallido')], default='enviado', max_length=10)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='alertas.alerta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
