# Generated by Django 5.1.15 on 2026-09-24 00:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='reportes/%Y/%m/')),
                ('ubicacion_usuario', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('ubicacion_incendio', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('ciudadano', models.ForeignKey(limit_choices_to={'rol': 'ciudadano'}, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte ciudadano',
                'verbose_name_plural': 'reportes ciudadanos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='reportes_re_estado_9ada57_idx')],
            },
        ),
    ]
