# Generated by Django 5.1.15 on 2026-09-24 00:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaModeloML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'corrida del modelo',
                'verbose_name_plural': 'corridas del modelo',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='ZonaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('puntaje_recurrencia', models.FloatField()),
                ('cantidad_incendios_historicos', models.PositiveIntegerField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='prediccion.corridamodeloml')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_recurrentes', to='usuarios.municipio')),
            ],
            options={
                'verbose_name': 'zona recurrente',
                'verbose_name_plural': 'zonas recurrentes',
                'ordering': ['-puntaje_recurrencia'],
            },
        ),
    ]
