# Generated by Django 5.1.15 on 2026-09-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('administrador', 'Administrador'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
