# Generated by Django 5.1.15 on 2026-09-24 00:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDeforestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('IDEAM', 'IDEAM'), ('UNGRD', 'UNGRD')], max_length=10)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('anio', models.PositiveSmallIntegerField()),
                ('hectareas_afectadas', models.FloatField(blank=True, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deforestaciones', to='usuarios.municipio')),
            ],
            options={
                'verbose_name': 'histórico de deforestación',
                'verbose_name_plural': 'históricos de deforestación',
                'indexes': [models.Index(fields=['fuente', 'anio'], name='historico_h_fuente_026688_idx')],
            },
        ),
    ]
