# Generated by Django 5.1.15 on 2026-09-09 16:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocoIncendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('NASA_FIRMS', 'NASA FIRMS'), ('INPE_QUEIMADAS', 'INPE QUEIMADAS')], max_length=20)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('fecha_hora', models.DateTimeField(help_text='Momento de la detección satelital (UTC).')),
                ('confianza', models.CharField(blank=True, default='', max_length=10)),
                ('brillo_frp', models.FloatField(blank=True, null=True)),
                ('satelite', models.CharField(blank=True, default='', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Momento de ingesta al sistema.')),
            ],
            options={
                'indexes': [models.Index(fields=['fuente', 'fecha_hora'], name='satelital_f_fuente_6686f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('fuente', 'ubicacion', 'fecha_hora'), name='foco_incendio_unico_por_fuente_ubicacion_fecha')],
            },
        ),
    ]
