# Generated by Django 5.1.15 on 2026-09-24 00:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        ('satelital', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_disparador', models.CharField(choices=[('deteccion_satelital', 'Detección satelital'), ('coincidencia_geografica', 'Coincidencia geográfica'), ('acumulacion_reportes', 'Acumulación de reportes'), ('validacion_manual', 'Validación manual')], max_length=30)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('foco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='satelital.focoincendio')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='usuarios.municipio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AlertaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('es_disparador', models.BooleanField(default=False)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.alerta')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.reporteciudadano')),
            ],
        ),
        migrations.AddField(
            model_name='alerta',
            name='reportes',
            field=models.ManyToManyField(related_name='alertas', through='alertas.AlertaReporte', to='reportes.reporteciudadano'),
        ),
        migrations.AddConstraint(
            model_name='alertareporte',
            constraint=models.UniqueConstraint(fields=('alerta', 'reporte'), name='alerta_reporte_unico'),
        ),
    ]
